In [29]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
headers={'User-Agent':'Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.162 Safari/537.36'}


name=[]
rating=[]
review=[]
ct=[]
location=[]
salaries=[]
interviews=[]
jobs=[]
benefits=[]
photos=[]
hrt=[]


for page in range(1,26):

    url = f'https://www.ambitionbox.com/list-of-companies?ratings=4.5&sortBy=popular&locations=new-delhi,mumbai,bengaluru,hyderabad,pune,chennai,kolkata,gurgaon,noida,ahmedabad&page={page}'

    webpage = requests.get(url,headers=headers).text

    soup = BeautifulSoup(webpage,'lxml')

    company = soup.find_all('div',class_='companyCardWrapper')

    for i in company:

        name.append(i.find('h2','companyCardWrapper__companyName').text.strip())

        rating.append(i.find('div','rating_star_container').text.strip())

        review.append(i.find('span','companyCardWrapper__companyRatingCount').text.strip())

        temp = i.find('span','companyCardWrapper__interLinking').text.strip()

        if '|' in temp:
            ct.append(temp.split('|')[0].strip())
            location.append(temp.split('|')[1].strip())
        else:
            ct.append(temp)
            location.append(None)

        temp3 = i.find_all('span','companyCardWrapper__ActionCount')

        salaries.append(temp3[1].text.strip())
        interviews.append(temp3[2].text.strip())
        jobs.append(temp3[3].text.strip())
        benefits.append(temp3[4].text.strip())
        photos.append(temp3[5].text.strip())

        temp5 = i.find('span','companyCardWrapper__ratingHeader--high')

        if temp5:
            temp4 = i.find('span','companyCardWrapper__ratingValues')
            hrt.append(temp4.text.strip())
        else:
            hrt.append(None)

        temp6 = i.find('span','companyCardWrapper__ratingHeader--critical')

       

df = pd.DataFrame({

    'Company_Name':name,
    'Rating':rating,
    'Reviews':review,
    'Company_Type':ct,
    'Location':location,
    'Salaries':salaries,
    'Interviews':interviews,
    'Jobs':jobs,
    'Benefits':benefits,
    'Photos':photos,
    'Highly_Rated_For':hrt,


})


df.head(3)

,Company_Name,Rating,Reviews,Company_Type,Location,Salaries,Interviews,Jobs,Benefits,Photos,Highly_Rated_For
0,iEnergizer,4.6,(27.2k),BPO,Noida +53 other locations,24.8k,1.6k,90,549,29,"Salary, Company Culture, Work Life Balance"
1,Muthoot FinCorp,4.5,(13.2k),NBFC,Bengaluru +1121 other locations,9.4k,2.4k,46,286,103,"Company Culture, Work Life Balance, Job Security"
2,Indian Army,4.7,(6.3k),Defence & Aerospace,New Delhi +360 other locations,9.3k,212,--,745,12,"Job Security, Company Culture, Work Life Balance"

In [35]:
df.to_csv('Top_Companies_Data.csv', index=False)

In [33]:
pd.read_csv('Top_Companies_Data.csv').head()

,Company_Name,Rating,Reviews,Company_Type,Location,Salaries,Interviews,Jobs,Benefits,Photos,Highly_Rated_For
0,iEnergizer,4.6,(27.2k),BPO,Noida +53 other locations,24.8k,1.6k,90,549,29,"Salary, Company Culture, Work Life Balance"
1,Muthoot FinCorp,4.5,(13.2k),NBFC,Bengaluru +1121 other locations,9.4k,2.4k,46,286,103,"Company Culture, Work Life Balance, Job Security"
2,Indian Army,4.7,(6.3k),Defence & Aerospace,New Delhi +360 other locations,9.3k,212,--,745,12,"Job Security, Company Culture, Work Life Balance"
3,Kogta Financial India Limited,4.7,(4.1k),NBFC,New Delhi +260 other locations,1.9k,252,91,32,39,"Company Culture, Work Life Balance, Work Satis..."
4,Cloudnine Hospital,4.5,(3.9k),Healthcare,Bengaluru +46 other locations,3.1k,1.5k,25,119,7,"Company Culture, Skill Development, Work Life ..."

In [34]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Company_Name      500 non-null    object
 1   Rating            500 non-null    object
 2   Reviews           500 non-null    object
 3   Company_Type      500 non-null    object
 4   Location          452 non-null    object
 5   Salaries          500 non-null    object
 6   Interviews        500 non-null    object
 7   Jobs              500 non-null    object
 8   Benefits          500 non-null    object
 9   Photos            500 non-null    object
 10  Highly_Rated_For  500 non-null    object
dtypes: object(11)
memory usage: 43.1+ KB