In [5]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

name = []
cp = []
pp = []
hp = []

for page in range(1,50):  

    if page == 1:
        url = "https://steamcharts.com/top"
    else:
        url = f"https://steamcharts.com/top/p.{page}"

    response = requests.get(
        url,
        headers={
            "User-Agent": "Mozilla/5.0"
        }
    )

    soup = BeautifulSoup(response.text, "lxml")

    rows = soup.select("table tbody tr")

    for row in rows:

        game = row.select_one("td.game-name")
        nums = row.select("td.num")

        if game and len(nums) >= 3:

            name.append(game.text.strip())

            cp.append(
                nums[0].text.strip().replace(",", "")
            )

            pp.append(
                nums[1].text.strip().replace(",", "")
            )

            hp.append(
                nums[2].text.strip().replace(",", "")
            )

df = pd.DataFrame({
    "Name": name,
    "Current_Players": cp,
    "Peak_Players": pp,
    "Hours_Played": hp
})


for col in ["Current_Players", "Peak_Players", "Hours_Played"]:
    df[col] = pd.to_numeric(df[col], errors="coerce")

print(df.head())
print(df.shape)


df.to_csv("steamcharts_top_games.csv", index=False)

                  Name  Current_Players  Peak_Players  Hours_Played
0     Counter-Strike 2          1010027       1285624     604722064
1               Dota 2           760541        981123     441705243
2  PUBG: BATTLEGROUNDS           559433        792142     241146580
3          How to Fish           233562        309232       5019425
4        Apex Legends™           193177        291356      90075008
(1225, 4)

In [6]:
df.head()

                  Name  Current_Players  Peak_Players  Hours_Played
0     Counter-Strike 2          1010027       1285624     604722064
1               Dota 2           760541        981123     441705243
2  PUBG: BATTLEGROUNDS           559433        792142     241146580
3          How to Fish           233562        309232       5019425
4        Apex Legends™           193177        291356      90075008

In [7]:
Game_Data=df

In [8]:
Game_Data.sample(5)

,Name,Current_Players,Peak_Players,Hours_Played
307,V Rising,3429,7910,2857103
1129,The Crew™ 2,472,878,336620
453,inZOI,1935,3105,1411616
945,Amazing Cultivation Simulator,640,805,322089
859,Everything is Crab: The Animal Evolution Rogue...,748,1390,654520

In [9]:
Game_Data.to_csv("Game_Data.csv", index=False)