In [1]:
import pandas as pd
import requests
from bs4 import BeautifulSoup

In [2]:
headers={'User-Agent':'Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.162 Safari/537.36'}

webpage=requests.get(
    'https://www.ambitionbox.com/list-of-companies?ratings=4.5&sortBy=popular&locations=new-delhi,mumbai,bengaluru,hyderabad,pune,chennai,kolkata,gurgaon,noida,ahmedabad',
    headers=headers
).text

In [3]:
soup=BeautifulSoup(webpage,'lxml')

In [4]:
company=soup.find_all('div',class_='companyCardWrapper')

In [5]:
name=[]
rating=[]
review=[]
ct=[]
location=[]
salaries=[]
interviews=[]
jobs=[]
benifits=[]
photos=[]
hrt=[]
crt=[]
for i in company:
    name.append(i.find('h2','companyCardWrapper__companyName').text.strip())
    rating.append(i.find('div','rating_star_container').text.strip())
    review.append(i.find('span','companyCardWrapper__companyRatingCount').text.strip())
    temp=(i.find('span','companyCardWrapper__interLinking').text.strip())
    temp = i.find('span','companyCardWrapper__interLinking').text.strip()

    parts = temp.split('|')

    ct.append(parts[0].strip())

    if len(parts) > 1:
        location.append(parts[1].strip())
    else:
        location.append(None)
    temp3=i.find_all('span','companyCardWrapper__ActionCount')
    salaries.append(temp3[1].text.strip())
    interviews.append(temp3[2].text.strip())
    jobs.append(temp3[3].text.strip())
    benifits.append(temp3[4].text.strip())
    photos.append(temp3[5].text.strip())
    temp5=i.find('span','companyCardWrapper__ratingHeader--high')
    if temp5:
        temp4=i.find('span','companyCardWrapper__ratingValues')
        hrt.append(temp4.text.strip())
    else:
        hrt.append(None)
    temp6=i.find('span','companyCardWrapper__ratingHeader--critical')
    if temp6:
        temp7=i.find('span','companyCardWrapper__ratingValues')
        crt.append(temp7.text.strip())
    else:
        crt.append(None)

In [6]:
df = pd.DataFrame({

    'Company_Name': name,
    'Rating': rating,
    'Reviews': review,
    'Company_Type': ct,
    'Location': location,
    'Salaries': salaries,
    'Interviews': interviews,
    'Jobs': jobs,
    'Benefits': benifits,
    'Photos': photos,
    'Highly_Rated_For': hrt,
    'Critically_Rated_For': crt

})

df

,Company_Name,Rating,Reviews,Company_Type,Location,Salaries,Interviews,Jobs,Benefits,Photos,Highly_Rated_For,Critically_Rated_For
0,iEnergizer,4.5,(27.9k),BPO,Noida +55 other locations,25.4k,1.7k,87,938,30,"Company Culture, Work Life Balance, Work Satis...",None
1,Muthoot FinCorp,4.5,(13.5k),NBFC,Bengaluru +1139 other locations,9.9k,2.4k,68,326,104,"Company Culture, Work Life Balance, Job Security",None
2,Indian Army,4.7,(6.5k),Defence & Aerospace,New Delhi +377 other locations,9.5k,216,--,755,15,"Job Security, Company Culture, Work Life Balance",None
3,Cloudnine Hospital,4.5,(4.2k),Healthcare,Bengaluru +48 other locations,3.3k,1.7k,18,235,7,"Company Culture, Job Security, Skill Development",None
4,Kogta Financial India Limited,4.6,(4.2k),NBFC,New Delhi +260 other locations,2.1k,252,98,40,39,"Company Culture, Work Life Balance, Work Satis...",None
5,Indian Air Force,4.6,(3.4k),Defence & Aerospace,New Delhi +138 other locations,5.5k,90,2,358,--,"Job Security, Skill Development, Company Culture",None
6,Marpu Foundation,4.9,(3.1k),Non-Profit,Hyderabad +61 other locations,61,266,--,8,5,"Company Culture, Work Life Balance, Work Satis...",None
7,Tekwissen,4.9,(2.1k),IT Services & Consulting,New Delhi +5 other locations,631,341,297,160,12,"Company Culture, Work Life Balance, Work Satis...",None
8,Labmentix,4.5,(2k),Bengaluru +35 other locations,None,48,659,--,95,1,"Work Life Balance, Skill Development, Company ...",None
9,Indian Navy,4.6,(1.7k),Defence & Aerospace,Mumbai +76 other locations,3.4k,40,--,240,2,"Job Security, Skill Development, Company Culture",None
10,mPokket,4.5,(1.7k),NBFC,Kolkata +23 other locations,1.8k,426,4,52,31,"Company Culture, Job Security, Skill Development",None
11,Hire In Global,4.9,(1.4k),Recruitment,Mumbai +63 other locations,8,304,--,36,--,"Company Culture, Work Life Balance, Work Satis...",None
12,Royal Migration Solutions,4.9,(1.4k),Other,New Delhi +12 other locations,5,1,--,1,--,"Company Culture, Work Life Balance, Work Satis...",None
13,Bluestock ™,4.5,(1.3k),FinTech,Pune +46 other locations,69,389,--,2,1,"Work Life Balance, Work Satisfaction, Skill De...",None
14,Kinara Capital,4.5,(1.2k),NBFC,Bengaluru +118 other locations,2.2k,136,--,209,41,"Company Culture, Work Life Balance, Work Satis...",None
15,Wonder Home Finance,4.6,(1.1k),NBFC,New Delhi +121 other locations,808,192,3,9,31,"Company Culture, Work Life Balance, Work Satis...",None
16,Northcorp Software,4.8,(1.1k),IT Services & Consulting,Gurugram +7 other locations,229,867,--,54,1,"Company Culture, Work Life Balance, Work Satis...",None
17,Jet Airways,4.6,(1.1k),Aviation,Mumbai +45 other locations,1.8k,27,--,175,--,"Work Satisfaction, Company Culture, Work Life ...",None
18,Nippon Life India Asset Management,4.6,(1.1k),Financial Services,Mumbai +189 other locations,1.6k,158,70,27,--,"Work Life Balance, Company Culture, Job Security",None
19,Incheon Motors,4.7,(1k),Automobile,New Delhi +16 other locations,367,297,11,7,7,"Company Culture, Job Security, Skill Development",None

In [7]:
data=df.iloc[:,0:11]

In [8]:
data

,Company_Name,Rating,Reviews,Company_Type,Location,Salaries,Interviews,Jobs,Benefits,Photos,Highly_Rated_For
0,iEnergizer,4.5,(27.9k),BPO,Noida +55 other locations,25.4k,1.7k,87,938,30,"Company Culture, Work Life Balance, Work Satis..."
1,Muthoot FinCorp,4.5,(13.5k),NBFC,Bengaluru +1139 other locations,9.9k,2.4k,68,326,104,"Company Culture, Work Life Balance, Job Security"
2,Indian Army,4.7,(6.5k),Defence & Aerospace,New Delhi +377 other locations,9.5k,216,--,755,15,"Job Security, Company Culture, Work Life Balance"
3,Cloudnine Hospital,4.5,(4.2k),Healthcare,Bengaluru +48 other locations,3.3k,1.7k,18,235,7,"Company Culture, Job Security, Skill Development"
4,Kogta Financial India Limited,4.6,(4.2k),NBFC,New Delhi +260 other locations,2.1k,252,98,40,39,"Company Culture, Work Life Balance, Work Satis..."
5,Indian Air Force,4.6,(3.4k),Defence & Aerospace,New Delhi +138 other locations,5.5k,90,2,358,--,"Job Security, Skill Development, Company Culture"
6,Marpu Foundation,4.9,(3.1k),Non-Profit,Hyderabad +61 other locations,61,266,--,8,5,"Company Culture, Work Life Balance, Work Satis..."
7,Tekwissen,4.9,(2.1k),IT Services & Consulting,New Delhi +5 other locations,631,341,297,160,12,"Company Culture, Work Life Balance, Work Satis..."
8,Labmentix,4.5,(2k),Bengaluru +35 other locations,None,48,659,--,95,1,"Work Life Balance, Skill Development, Company ..."
9,Indian Navy,4.6,(1.7k),Defence & Aerospace,Mumbai +76 other locations,3.4k,40,--,240,2,"Job Security, Skill Development, Company Culture"
10,mPokket,4.5,(1.7k),NBFC,Kolkata +23 other locations,1.8k,426,4,52,31,"Company Culture, Job Security, Skill Development"
11,Hire In Global,4.9,(1.4k),Recruitment,Mumbai +63 other locations,8,304,--,36,--,"Company Culture, Work Life Balance, Work Satis..."
12,Royal Migration Solutions,4.9,(1.4k),Other,New Delhi +12 other locations,5,1,--,1,--,"Company Culture, Work Life Balance, Work Satis..."
13,Bluestock ™,4.5,(1.3k),FinTech,Pune +46 other locations,69,389,--,2,1,"Work Life Balance, Work Satisfaction, Skill De..."
14,Kinara Capital,4.5,(1.2k),NBFC,Bengaluru +118 other locations,2.2k,136,--,209,41,"Company Culture, Work Life Balance, Work Satis..."
15,Wonder Home Finance,4.6,(1.1k),NBFC,New Delhi +121 other locations,808,192,3,9,31,"Company Culture, Work Life Balance, Work Satis..."
16,Northcorp Software,4.8,(1.1k),IT Services & Consulting,Gurugram +7 other locations,229,867,--,54,1,"Company Culture, Work Life Balance, Work Satis..."
17,Jet Airways,4.6,(1.1k),Aviation,Mumbai +45 other locations,1.8k,27,--,175,--,"Work Satisfaction, Company Culture, Work Life ..."
18,Nippon Life India Asset Management,4.6,(1.1k),Financial Services,Mumbai +189 other locations,1.6k,158,70,27,--,"Work Life Balance, Company Culture, Job Security"
19,Incheon Motors,4.7,(1k),Automobile,New Delhi +16 other locations,367,297,11,7,7,"Company Culture, Job Security, Skill Development"